### ISSUE TITLE
Umbrella ticket for new features

### ISSUE THREAD

**Issue by DimitarTasev** [DimitarTasev/PythonWorkoutManager#5]
- [ ] Rest tracking after set
- [ ] Rest tracking after exercise 
- [ ] Start_time in workout name #Style2 outlined format in WorkoutDesignDocument
- [ ] Duration in workout
TODO_low_priority:
- [ ] Support whitespace to separate workout and workout information
- [ ] Support '-' as re-use from cache for ONLY weights or reps
